server:
  port: 9000

spring:
  application:
    name: sc-gateway

  cloud:
    gateway:
      routes:
        - id: hello_route # 새로 추가할 라우트의 ID
          uri: http://localhost:8765 # 타겟 서비스의 URI
          predicates:
            - Path=/hello # 매칭할 경로 (정확히 /hello)

        - id: abc2hello_route
          uri: http://localhost:8765
          predicates:
            - Path=/abc

        - id: def2hello_route
          uri: http://localhost:8765
          predicates:
            - Path=/def
          filters:
            - RewritePath=/def, /hello

#logging:
#  level:
#    # Spring CLoud Gateway의 라우팅, 필터 체인 관련 로그
#    org.springframework.cloud.gateway: DEBUG
#    # 리액터(Netty) 네트워크 통신 로그 (요청/응답 상세)
#    reactor.netty: DEBUG
#    # Spring Webflux (게이트웨이 기반 기술) 관련 로그
#    org.springframework.web.reactive: DEBUG
