server:
  port: 9000

spring:
  application:
    name: sc-gateway

  cloud:
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true

    gateway:
      routes:
        - id: hello_route
          uri: ${HELLO_SERVICE_URI:http://localhost:8765}
          predicates:
            - Path=/hello

        - id: abc2hello_route
          uri: ${HELLO_SERVICE_URI:http://localhost:8765}
          predicates:
            - Path=/abc

        - id: def2hello_ok_route
          uri: ${HELLO_SERVICE_URI:http://localhost:8765}
          predicates:
            - Path=/def
          filters:
            - RewritePath=/def, /hello

        - id: users_users_route # 통합된 라우트 ID
          uri: lb://USER-SERVICE # USERS 서비스로 라우팅
          predicates:
            - Path=/api/users/** # 클라이언트 요청 경로 (뒤에 무엇이 오든 상관 없음)
          filters:
              # '/api/uuu' 접두사를 제거하고 남은 경로를 전달합니다.
            - RewritePath=/api/users/(?<segment>.*), /${segment}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
    org.springframework.web.reactive: DEBUG