server:
  port: 9000

spring:
  application:
    name: sc-gateway

  cloud:
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true

    gateway:
      routes:
        - id: hello_route
          uri: ${HELLO_SERVICE_URI:http://localhost:8765}
          predicates:
            - Path=/hello

        - id: abc2hello_route
          uri: ${HELLO_SERVICE_URI:http://localhost:8765}
          predicates:
            - Path=/abc

        - id: def2hello_ok_route
          uri: ${HELLO_SERVICE_URI:http://localhost:8765}
          predicates:
            - Path=/def
          filters:
            - RewritePath=/def, /hello

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
    org.springframework.web.reactive: DEBUG