server:
  port: 9000

spring:
  application:
    name: only-apigateway-service

  cloud:
    gateway:
      routes:
        - id: hello_route
          uri: http://localhost:8765
          predicates:
            - Path=/hello